#A quick script that renames the audiofiles generated by Mits for use in the Experiment Script

MMWordList <- read.csv("F:/Google Drive/Experiments/Collaborations/MitsMark/Stimuli/WordLists.csv")

setwd("F:/Google Drive/Experiments/Collaborations/MitsMark/Stimuli/")

file.rename(from = paste0(MMWordList$Stimulus, ".wav" ), to = paste0(MMWordList$Word, ".wav"))
